TRAIN:
  ENABLE: True
  DATASET: Ssv2
  BATCH_SIZE: 56
  EVAL_PERIOD: 35
  CHECKPOINT_PERIOD: 35
  AUTO_RESUME: True
  CHECKPOINT_EPOCH_RESET: True
  CHECKPOINT_FILE_PATH:  /jmain02/home/J2AD001/wwp01/txp48-wwp01/motionformer/checkpoint/motionformer/ssv2lt_init/checkpoint_epoch_00035.pyth
  CLS_BAL_EPOCH: 0
  RESET_CLS_EPOCH: 0
  RECONSTRUCT: True
  RECONSTRUCT_BANK_SIZE: 8
  RECONSTRUCT_CONTRIBUTION: "no-fst"
  RECONSTRUCT_APPLICATION: "log_params"
  RECONSTRUCT_WEIGHT: 0.5
  FEATURE_MIXUP_PROB: 0.5
  RECONSTRUCT_L: 0.6
  RECONSTRUCT_H: 0.001
  RECONSTRUCT_D: 0.25
DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 4
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  MEAN: [0.5, 0.5, 0.5]
  STD: [0.5, 0.5, 0.5]
  PATH_TO_DATA_DIR: /jmain02/home/J2AD001/wwp01/txp48-wwp01/ssv2-annotations-lt/
  PATH_PREFIX: /jmain02/home/J2AD001/wwp01/shared/data/ssv2/frames/
  INV_UNIFORM_SAMPLE: True
  RANDOM_FLIP: False
  REVERSE_INPUT_CHANNEL: True
  USE_RAND_AUGMENT: True
  RE_PROB: 0.0
  USE_REPEATED_AUG: False
  USE_RANDOM_RESIZE_CROPS: False
  COLORJITTER: False
  GRAYSCALE: False
  GAUSSIAN: False
SOLVER:
  # BASE_LR: 1e-4
  BASE_LR: 1e-5
  LR_POLICY: steps_with_relative_lrs
  LRS: [1, 0.1, 0.01]
  STEPS: [0, 20, 30]
  MAX_EPOCH: 35
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-2
  WARMUP_EPOCHS: 0.0
  OPTIMIZING_METHOD: adamw
  USE_MIXED_PRECISION: True
  SMOOTHING: 0.0
SLOWFAST:
  ALPHA: 8
VIT:
  PATCH_SIZE: 16
  PATCH_SIZE_TEMP: 2
  CHANNELS: 3
  EMBED_DIM: 768
  DEPTH: 12
  NUM_HEADS: 12
  MLP_RATIO: 4
  QKV_BIAS: True
  VIDEO_INPUT: True
  TEMPORAL_RESOLUTION: 8
  USE_MLP: True
  DROP: 0.0
  POS_DROPOUT: 0.0
  DROP_PATH: 0.2
  IM_PRETRAINED: True
  HEAD_DROPOUT: 0.0
  HEAD_ACT: tanh
  PRETRAINED_WEIGHTS: vit_1k
  ATTN_LAYER: trajectory
MODEL:
  NUM_CLASSES: 174
  ARCH: slow
  MODEL_NAME: VisionTransformer
  LOSS_FUNC: soft_target_cross_entropy
TEST:
  ENABLE: True
  DATASET: Ssv2
  BATCH_SIZE: 112
  NUM_ENSEMBLE_VIEWS: 10
  NUM_SPATIAL_CROPS: 3
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 4
RNG_SEED: 0
OUTPUT_DIR: .
TENSORBOARD:
  ENABLE: True
SSV2:
  TRAIN_COUNTS: [188, 46, 15, 14, 20, 148, 1982, 13, 38, 61, 65, 113, 180, 6, 101, 978, 408, 117, 1085, 357, 274, 27, 37, 23, 9, 6, 8, 759, 624, 469, 373, 655, 160, 22, 26, 25, 491, 566, 14, 16, 73, 59, 68, 2099, 51, 2357, 241, 105, 39, 196, 24, 5, 5, 7, 6, 299, 1418, 24, 5, 55, 6, 7, 8, 8, 7, 41, 70, 448, 515, 17, 8, 28, 142, 222, 341, 22, 9, 8, 5, 11, 29, 213, 81, 75, 31, 13, 540, 594, 7, 18, 15, 7, 6, 2224, 1872, 17, 10, 19, 97, 839, 1144, 390, 93, 173, 204, 45, 1498, 1273, 11, 2500, 16, 5, 687, 10, 1030, 10, 10, 19, 21, 32, 109, 63, 263, 87, 43, 798, 42, 78, 29, 722, 231, 9, 13, 12, 166, 326, 5, 5, 6, 33, 154, 12, 11, 1206, 137, 312, 1673, 131, 883, 929, 286, 1582, 252, 90, 36, 57, 20, 84, 12, 9, 428, 14, 34, 5, 1343, 53, 126, 122, 50, 6, 30, 1769, 48, 18]
